# application.propertiesをこっちに変えても勝手にスキャンして設定読み込むよ。
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  messages:
    basename: messages
    cache-duration: -1
    encoding: UTF-8
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: localhost
    port: 1025
  thymeleaf:
    check-template-location: false
users:
  intervel: 1001
#mailhog
#http://localhost:8080/mail/mailsender
#http://localhost:8080/mail/javamailsender
mail:
    host: mailhog
    port: 1025
    username: ""
    password: ""
#    host: smtp.gmail.com
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.starttls.enable: true


#  users:
#    id: user-dev
#    name: 開発ユーザー
## spring.profiles.activeにアクティブなプロファイルを指定する
#spring:
#  profiles:
#    active: dev
# 
## "---"でプロファイルを区切る
## spring.profilesにプロファイル名を書く
#---
#spring:

#---